version: 0.0
os: linux
# prettier-ignore
files:
  - source: /
    destination: /anime-browser/exec/

# prettier-ignore
permissions:
  - object: /anime-browser/exec/
    owner: wsrv_adm
    group: wsrv_adm

# prettier-ignore
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/remove
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
